In [2]:
import torch

In [3]:
x = torch.tensor(3.0)
print(x, x.shape)

tensor(3.) torch.Size([])


In [4]:
x = torch.tensor([[1, 2], [3, 4]])
print(x, x.shape)
print(x.grad)

tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
None


In [5]:
print(x + 4)

tensor([[5, 6],
        [7, 8]])


In [6]:
print(x*34)

tensor([[ 34,  68],
        [102, 136]])


In [7]:
print(x.T)

tensor([[1, 3],
        [2, 4]])


In [8]:
x = torch.tensor(3.0, requires_grad=True)
print(x, x.shape)

tensor(3., requires_grad=True) torch.Size([])
